name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build static files
        run: npm run build
      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./public
